// MongoDB Playground
// To disable this template go to Settings | MongoDB | Use Default Template For Playground.
// Make sure you are connected to enable completions and to be able to run a playground.
// Use Ctrl+Space inside a snippet or a string literal to trigger completions.

// Select the database to use.
use('mongodbVSCodePlaygroundDB');
use disect
db.createCollection("charities")

// The drop() command destroys all data from a collection.
// Make sure you run it against the correct database and collection.
db.sales.drop();

// Insert a few documents into the sales collection.
db.charities.insertMany([
  { '_id': 1, 'category': 'Labor Rights', 'name': 'Clean Clothes Campaign', 'main_website_url': 'https://cleanclothes.org/', 'donation_url': 'https://cleanclothes.org/donate', 'short_description': 'The Clean Clothes Campaign is a global network of over 235 organizations in more than 45 countries. It aims to improve the working conditions of the garment and sportswear industries by connecting various organizations, including grassroots unions, trade unions, and feminist organizations. The campaign is worker-centered and utilizes a horizontal operational structure to address local and global problems. They offer direct solidarity support to workers fighting against specific worker rights violations and co-develop global campaigns to achieve systemic goals. The campaign educates and mobilizes consumers, lobbies companies and governments, and cooperates with other labor rights campaigns. All members, partners, and associates are dedicated to empowering workers to ensure their fundamental rights are respected.' },
  { '_id': 2, 'category': 'Labor Rights', 'name': 'Workers Rights Consortium', 'main_website_url': 'https://www.workersrights.org/', 'donation_url': 'https://www.workersrights.org/donate', 'short_description': "The Worker Rights Consortium (WRC) is an independent labor rights monitoring organization that investigates working conditions in factories worldwide to combat sweatshop conditions and protect workers' rights. They conduct worker-centered investigations, issue public reports on factories producing for major brands, and aid workers in their efforts to end violations and defend their workplace rights. The WRC seeks to foster binding agreements between worker representatives and global corporations to bring systemic change to global supply chains and generate concrete gains for workers. Founded in 2000, the WRC assists universities and works with government entities seeking to enforce human rights standards. They have investigators in 12 countries and work with hundreds of civil society organizations worldwide." },
  { '_id': 3, 'category': 'Labor Rights', 'name': 'International Labor Rights Forum', 'main_website_url': 'https://laborrights.org/', 'donation_url': 'https://laborrights.app.neoncrm.com/np/clients/laborrights/donation.jsp', 'short_description': "The International Labor Rights Forum is a human rights organization that works to advance dignity and justice for workers in the global economy. Their core work includes holding global corporations accountable for labor rights violations, advancing policies and laws that protect workers, and strengthening workers' ability to advocate for their rights. They work with trade unions, faith-based organizations, and community groups to support workers and their families, and have led initiatives such as making apparel factories safe in Bangladesh, stopping the exploitation of children in Uzbekistan's cotton fields, and increasing the income of farm workers in West Africa's cocoa fields. Their mission is to achieve dignity and justice for workers worldwide, and they value labor rights, social justice, economic development, child labor and forced labor eradication, social change, and consumer advocacy for just and dignified jobs." },
  { '_id': 4, 'category': 'Labor Rights', 'name': 'Labour Behind the Label', 'main_website_url': 'https://labourbehindthelabel.org/', 'donation_url': 'https://labourbehindthelabel.org/donate/', 'short_description': "Labour Behind the Label is a UK-based campaign that works to improve conditions and empower workers in the global garment industry, where human rights abuses are systemic. The campaign raises public awareness, promotes collective action from consumers, pressures companies to take responsibility for worker's rights throughout their supply chains, works with trade unions, and lobbies governments and policy makers to legislate and protect garment workers' human rights. They believe that a living wage and working without fear for your life are basic human rights and work to make them a reality in the garment industry. The campaign has two decades of experience in awareness raising, research, and lobbying in support of workers' demands for improved pay and conditions. They are a workers' cooperative representing the Clean Clothes Campaign in the UK and work with over 250 partner organizations worldwide." },
  { '_id': 5, 'category': 'Labor Rights', 'name': 'Maquila Solidarity Network', 'main_website_url': ' https://www.maquilasolidarity.org/en', 'donation_url': 'https://www.maquilasolidarity.org/en/civicrm/contribute/transact?reset=1&id=1', 'short_description': "The Maquila Solidarity Network (MSN) is a labor and women's rights organization that has worked for over 25 years to support workers in the global garment and footwear industries in achieving improved wages, working conditions, and respect for their rights. They work with trade unions, women's and labor rights organizations to combat factory-level labor rights violations and achieve systemic changes in the industry towards decent work and living wages. MSN engages with and campaigns against international apparel and footwear companies to hold them accountable for labor rights abuses in their supply chains. They also advocate for governments to adopt legislation and policies that require companies to conduct human rights due diligence to identify, prevent, mitigate, and account for potential harm to workers in their global supply chains. Based in Toronto, Canada, MSN has a small office in Mexico City and focuses its work in Central America and Mexico." },
  { '_id': 6, 'category': 'Labor Rights', 'name': 'Freedom United', 'main_website_url': 'https://www.freedomunited.org/', 'donation_url': 'https://www.freedomunited.org/donate/', 'short_description': "Freedom United is a charity that aims to create a world free of modern slavery and human trafficking. They work to educate and empower their community to create systemic change and make key stakeholders allies in the fight against modern slavery. They believe that mass action, survivor empowerment, and systemic change are necessary to end modern slavery. They also prioritize transparency, integrity, and community in their work. Freedom United uses the term 'modern slavery' as an umbrella term for extreme forms of exploitation, including forced labor, forced marriage, debt bondage, bonded labor, trafficking for labor and sexual exploitation. Their work is made possible through the generosity of their supporters and survivor advocates are vital to ending modern slavery." },
  { '_id': 7, 'category': 'Carbon Emissions', 'name': 'Clean Air Task Force', 'main_website_url': 'https://www.catf.us/', 'donation_url': 'https://donate.catf.us/page/39127/donate/1', 'short_description': 'Clean Air Task Force vision is to meet the world’s rising energy demand in a way that is financially, socially, and environmentally sustainable. Their goal is to push the technology and policy changes needed to achieve a zero-emissions, high-energy planet at an affordable cost.' },
  { '_id': 8, 'category': 'Carbon Emissions', 'name': 'Carbon180', 'main_website_url': 'https://carbon180.org/', 'donation_url': 'https://carbon180.org/donate', 'short_description': "Carbon180 is a new breed of climate NGO dedicated to bringing together the people, resources, and vision to realize a carbon-removing world. Their vision is to eliminate legacy carbon emissions and create a livable climate in which current and future generations can thrive. They aim to design and champion equitable, science-based policies that bring carbon removal solutions to gigaton scale." },
  { '_id': 9, 'category': 'Carbon Emissions', 'name': 'Evergreen', 'main_website_url': 'https://www.evergreenaction.com/', 'donation_url': 'https://secure.actblue.com/donate/evergreenaction?refcode=alertbar', 'short_description': "Evergreen is leading the fight to put bold climate action at the top of America's agenda, implement an all-out mobilization to defeat climate change and create millions of good union jobs in a just and thriving clean energy economy." },
  { '_id': 10, 'category': 'Environmentally Friendly', 'name': 'The Nature Conservancy', 'main_website_url': 'https://www.nature.org/en-us/', 'donation_url': 'https://preserve.nature.org/page/80429/donate/1', 'short_description': "The Nature Conservancy is a global environmental nonprofit working to create a world where people and nature can thrive. Their mission is To conserve the lands and waters on which all life depends. Their vision is A world where the diversity of life thrives, and people act to conserve nature for its own sake and its ability to fulfill our needs and enrich our lives." },
  { '_id': 11, 'category': 'Environmentally Friendly', 'name': 'Well Done Foundation', 'main_website_url': 'https://welldonefoundation.org/', 'donation_url': 'https://welldonefoundation.org/donate-to-wdf/', 'short_description': "The vision for the Well Done Foundation (WDF) came together during the Summer of 2019 after visiting the legacy Kevin-Sunburst Oilfield in Northern Montana and seeing firsthand the impacts of Orphan and Abandoned Oil & Gas Wells on the industry, communities and the environment. That encounter left such a strong impression that Curtis felt compelled to take immediate action through leaving the oil patch better than the way that he had found it." },
  { '_id': 12, 'category': 'Environmentally Friendly', 'name': 'Climate Foundation', 'main_website_url': 'https://www.climatefoundation.org/', 'donation_url': 'https://www.climatefoundation.org/donate-2023.html', 'short_description': "Climate Foundation is an organization that aims to provide enough food for humans and other species as the world becomes overpopulated. They also aim to create safe places for thousands of species of the 8.7 million+ species losing their habitat.​ They also have a goal to find and deploy carbon balancing systems that mimic the one's that mother nature once used." },
  { '_id': 13, 'category': 'Environmentally Friendly', 'name': 'Evergreen', 'main_website_url': 'https://www.evergreenaction.com/', 'donation_url': 'https://secure.actblue.com/donate/evergreenaction?refcode=alertbar', 'short_description': "Evergreen is leading the fight to put bold climate action at the top of America's agenda, implement an all-out mobilization to defeat climate change and create millions of good union jobs in a just and thriving clean energy economy." },
  { '_id': 14, 'category': 'Animal Cruelty', 'name': 'Cruelty Free International', 'main_website_url': 'https://crueltyfreeinternational.org/  ', 'donation_url': 'https://crueltyfreeinternational.org/donate', 'short_description': "Cruelty Free International is the leading organization working to create a world where nobody wants or believes we need to experiment on animals. Established in 1898, Cruelty Free International is firmly rooted in the early social justice movement.  Our founder, Frances Power Cobbe, was a formidable women’s rights campaigner and philanthropist.  Previously known as the ‘British Union for the Abolition of Vivisection’ or ‘BUAV’, today Cruelty Free International is the leading organization working globally to consign animal experiments to the history books." },
  { '_id': 15, 'category': 'Animal Cruelty', 'name': 'Johns Hopkins Bloomberg School of Public Health', 'main_website_url': 'https://caat.jhsph.edu/  ', 'donation_url': 'https://caat.jhsph.edu/giving/index.html', 'short_description': "The Johns Hopkins Center for Alternatives to Animal Testing (CAAT), founded in 1981, is part of the Johns Hopkins University Bloomberg School of Public Health, with a European branch (CAAT-Europe) located at the University of Konstanz, Germany. We promote humane science by supporting the creation, development, validation, and use of alternatives to animals in research, product safety testing, and education. We seek to effect change by working with scientists in industry, government, and academia to find new ways to replace animals with non-animal methods, reduce the numbers of animals necessary, or refine methods to make them less painful or stressful to the animals involved." },
  { '_id': 16, 'category': 'LGBTQ', 'name': 'The Trevor Project', 'main_website_url': 'https://www.thetrevorproject.org/  ', 'donation_url': 'https://www.thetrevorproject.org/', 'short_description': "The Trevor Project is a nonprofit organization dedicated to ending suicide among lesbian, gay, bisexual, transgender, queer & questioning young people. Their mission is to provide direct suicide prevention and crisis intervention services through phone, text, and chat. They also offer peer support through the world's largest safe-space social networking community, research evaluations to improve services, public education, and advocacy for policies and laws that protect LGBTQ youth. Their goal is to create a world where all LGBTQ young people see a bright future for themselves. Their guiding principles include diversity & inclusion, youth-centricity, growth, quality, innovation, and a best-in-class team. The Trevor Project estimates that over 1.8 million LGBTQ youth in the United States seriously consider suicide each year." },
  { '_id': 17, 'category': 'LGBTQ', 'name': 'Human Rights Campaign', 'main_website_url': 'https://www.hrc.org/', 'donation_url': 'https://give.hrc.org/page/118560/donate/1?ea.tracking.id=or_gnr_hrc_homepage2022', 'short_description': "By inspiring and engaging individuals and communities, the Human Rights Campaign strives to end discrimination against LGBTQ+ people and realize a world that achieves fundamental fairness and equality for all. HRC envisions a world where lesbian, gay, bisexual, transgender and queer people plus community members who use different language to describe identity are ensured equality and embraced as full members of society at home, at work and in every community." },
  { '_id': 18, 'category': 'LGBTQ', 'name': 'Point Foundation', 'main_website_url': 'https://pointfoundation.org/', 'donation_url': 'https://pointfoundation.org/support/donate', 'short_description': "As an LGBTQ foundation, we empower promising lesbian, gay, bisexual, transgender, and queer students to achieve their full academic and leadership potential – despite the obstacles often put before them – so they can better make a significant impact on society. We provide financial support, a community of peers, leadership training, and mentorship, to US college students from around the world. Point also generates research to document the challenges LGBTQ students face on US campuses so that we can provide data and resources to help mitigate these issues." },
  { '_id': 19, 'category': 'LGBTQ', 'name': 'Boston Alliance of LGBTQ+ Youth', 'main_website_url': ' https://www.bagly.org/', 'donation_url': 'https://www.bagly.org/donate', 'short_description': "The Boston Alliance of Gay, Lesbian, Bisexual and Transgender Youth, is a youth-led, adult-supported social support organization, committed to social justice and creating, sustaining, and advocating for programs, policies, and services for the LGBTQ+ youth community. BAGLY believes in creating safe space. In BAGLY’s values: Respect, Diversity, Social Justice, Youth Leadership. In feeling safe. In having fun. In equal access to public accommodations, employment, and credit for transgender and gender variant people. In building a strong, youth-led social justice community. In conflict resolution. In change. In healthy relationships. In sexual freedom, and being sex positive. In health education. In safer sex." },
  { '_id': 20, 'category': 'LGBTQ', 'name': 'Campaign for Southern Equality', 'main_website_url': 'https://southernequality.org/', 'donation_url': 'https://southernequality.org/donate/', 'short_description': "At the Campaign for Southern Equality, we’re working to build a South where LGBTQ people are equal in every sphere of life. More than one third of all LGBTQ Americans live in the South. But our community lacks basic legal protections, faces political attacks, and experiences health and income inequities. LGBTQ Southerners also live each day with courage and strength and are doing heroic work to promote equality in their hometowns. And every day, we hear powerful stories about how the South is changing." },
  { '_id': 21, 'category': 'LGBTQ', 'name': 'The Dru Project', 'main_website_url': 'https://thedruproject.org/about', 'donation_url': 'https://thedruproject.app.neoncrm.com/np/clients/thedruproject/donation.jsp?campaign=7', 'short_description': "The Dru Project is an LGBTQ+ advocacy organization on a mission to spread love across the nation and promote gay straight alliances. We are doing this by creating a curriculum for high school GSAs to use, should they wish to adopt our program. We are also offering scholarships to students who truly exemplify Drew's spirit for inclusion and unity." },
  { '_id': 22, 'category': 'LGBTQ', 'name': ' Gays & Lesbians Living in a Transgender Society', 'main_website_url': 'https://www.glitsinc.org/', 'donation_url': 'https://www.glitsinc.org/checkout/donate?donatePageId=609aa70f7ded3d2e926', 'short_description': "GLITS creates holistic solutions to the health and housing crises faced by TGBLQIA+ individuals experiencing systemic discrimination at intersecting oppressions impacted by racism and criminalization, through a lens of harm reduction, human rights principles, social justice and community empowerment, imbued with a commitment to empowerment and pride in finding solutions in our own community." },
  { '_id': 23, 'category': 'Black Owned', 'name': 'Black Girls Code', 'main_website_url': 'https://wearebgc.org/', 'donation_url': 'https://wearebgc.org/donate/', 'short_description': "Black Girls CODE is a nonprofit organization founded in 2011 to improve the pipeline of Black girls in tech by introducing them to skills in computer programming and technology. Their mission is to close the opportunity gap for Black women and girls and to show the world that Black girls can code, lead, innovate, and engineer their own futures. Their core programming includes web design, game design, mobile and app design, and robotics. They aim to create stronger economies and more equitable societies through diversity and inclusion." },
  { '_id': 24, 'category': 'Black Owned', 'name': 'Black Connect', 'main_website_url': 'https://www.blackconnect.org/', 'donation_url': 'https://www.blackconnect.org/donate', 'short_description': "Black Connect is a national, membership-based organization focused on eliminating the racial wealth gap in America by increasing the number and success rate of Black-owned businesses, with an emphasis on low and moderate-income communities. Founded in 2019, Black Connect is the charitable arm of BlackConnect.com, the only Black-owned business and social networking platform designed to enable entrepreneurial activities and promote socioeconomic growth and empowerment of the Black community. The organization's mission is to create equal opportunities for Black people to be self-reliant and self-sustaining. Their vision is to see thriving Black communities across every state in America and throughout the African diaspora." },
  { '_id': 25, 'category': 'Fashion Sustainability', 'name': 'Fashion Revolution', 'main_website_url': ' https://www.fashionrevolution.org/', 'donation_url': 'https://www.fashionrevolution.org/donate/', 'short_description': "Fashion Revolution is a global movement founded in response to the Rana Plaza disaster in 2013. Its mission is to eliminate human and environmental exploitation in the global fashion industry, promote safe and fair working conditions, and raise awareness among consumers about the impacts of their clothing. Fashion Revolution conducts research, educates people about the industry's systemic challenges, mobilizes communities, and advocates for policy changes. The organization aims to show that change is possible and to encourage consumers to consume less, value quality, and take better care of their clothes. The organization is funded through donations, grants, and sponsorships, and it follows strict and transparent ethical funding policies." },
  { '_id': 26, 'category': 'American Owned', 'name': 'Made in America', 'main_website_url': 'https://madeinamerica.org/', 'donation_url': '', 'short_description': "MadeInAmerica.org is a non-profit organization focused on driving economic development and job growth by changing consumer behavior through education. The organization plans to drive a 3-5% shift in consumer behavior towards American-made products through education via advertising, media engagement programs, and educational events and workshops. The goal is to create between 800 thousand to 1.33 million new jobs and at least 192.5 billion dollars in incremental financial impact to the American economy. The organization's purpose is to increase domestic manufacturing and buying American-made products to revitalize jobs across the country and improve the quality of life for manufacturing workers. Every dollar spent on American manufacturing returns at least $2.89, and for every job created in manufacturing, at least 5 other jobs are created in the local community and supply chain." },
]);

/*
// Run a find command to view items sold on April 4th, 2014.
db.sales.find({ date: { $gte: new Date('2014-04-04'), $lt: new Date('2014-04-05') } });

// Build an aggregation to view total sales for each product in 2014.
const aggregation = [
  { $match: { date: { $gte: new Date('2014-01-01'), $lt: new Date('2015-01-01') } } },
  { $group: { _id: '$item', totalSaleAmount: { $sum: { $multiply: [ '$price', '$quantity' ] } } } }
];

// Run the aggregation and open a cursor to the results.
// Use toArray() to exhaust the cursor to return the whole result set.
// You can use hasNext()/next() to iterate through the cursor page by page.
db.sales.aggregate(aggregation);
*/
